repos:
-   repo: local
    hooks:
    -   id: flake8
        name: Flake8
        description: Lints this repository using flake8.
        entry: pipenv run lint
        language: python
        types: [python]
        require_serial: true
